### ISSUE TITLE
Validating the model with only SOL and LF

### ISSUE THREAD

**Issue by AndyCheang** [cwig/start_follow_read#8]
Hi,

I am trying to reproduce the result of your model with only SOL and LF module by withdrawing HWR module on your model, we used the pre-train model that you provided.

We test the model with ICDAR dataset.
The performance of SOL is quite good, but LF has a little problem. Some of the testing samples, the result is good, just like below one. (Test-B-050003)
![fig1](https://user-images.githubusercontent.com/13713968/67930793-7fbd8280-fbfb-11e9-8638-544fd0158429.png)

 However, we found that some of the testing samples are weird, for example (Test-B-050006):
![fig2](https://user-images.githubusercontent.com/13713968/67931000-fa869d80-fbfb-11e9-979f-010b6c2d66ea.png)

I would appreciate some advice if you cloud share some idea to test the model. Is the issue related to the model input_height?

**Comment by Marcovaldong** [comment]
@AndyCheang  What the version of your PyTorch is? I am trying to reproduce this work and trying to test it on IAM dataset. When the version of PyTorch is 1.2.0, the result is like yours, the result of most samples is bad. But when I downgraded PyTorch to 0.3.1, the result of every sample in test set is even perfect. Below is the visulization of Test-B-050006. 

![050006 jpg npz](https://user-images.githubusercontent.com/17369988/68186647-9559f000-ffdf-11e9-8abc-282f86be0ba7.png)

@cwig  @herobd Now, I am trying to retrain SFR on IAM dataset, do you know how to preprocess the dataset?

**Comment by AndyCheang** [comment]
@Marcovaldong I am currently using pytorch 0.4.1. I will try to downgrade to 0.3.1 to see the result again. Thanks.

**Comment by AndyCheang** [comment]
After downgrade to pytorch 0.3.1, the result seems normal. Thanks for your advice. @Marcovaldong

**Comment by sambbhavgarg** [comment]
Hi @AndyCheang 
I have a couple of concerns -

1. I've started development with torch 0.4 to reproduce the weird results you got, because pip or conda didn't exactly let me download the exact versions for other dependencies (like torchvision) without --no-deps for torch 0.3.1.
2. On loading the state_dict for CRNN I get the following error - 
`RuntimeError: Error(s) in loading state_dict for CRNN:
        While copying the parameter named "rnn.rnn.weight_ih_l0", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 1024]).
        While copying the parameter named "rnn.rnn.weight_ih_l0_reverse", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 1024]).` 

This means that the defined architecture of the model and the model used to create the checkpoints differ. I tried changing the architecture settings and ended up with like 10 more errors like these.

What am I doing wrong?

Regards
Sambbhav

PS I didnt think this would need a separate issue in itself as (1) you guys are getting results (2) which means probably im doing smth rlly wrong.

**Comment by engreememad** [comment]
Hi @AndyCheang  and @Marcovaldong how are you?
Please l need a help in this code l need to understand why l have error "segmentation fault core dumped" on my dataset.. I tried to use the lf for 10000 images and it gives me this error
Please help me
